name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
      # trying to install npm packages 12
    - run: npm i -g npm@latest
    - run: npm i npm@latest
    - run: npm i allure-commandline@latest
    - name: Install dependencies 
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Copy backupHistory
      if: always()
      # trying to save history screens and info of previous runs if it is exists
      run: cp -r $(pwd)/docs/backupHistory/. $(pwd)/allure-results
    - name: Create Report
      if: always()
      # trying to save history of previous runs if it is exists
      run: npx allure generate ./DemoProject/allure-results --clean
    - name: Create bacup directory
      if: always()
      # trying to create backup directory
      run: mkdir allure-report/backupHistory 
    - name: Backup history tests
      if: always()
      # trying to backup screens and info test
      run: cp -r $(pwd)/allure-results/*.* $(pwd)/allure-report/backupHistory
    - name: Display structure of backup history files
      if: always()
      run: ls -R
      working-directory: allure-report/backupHistory
    - name: Upload artifact allure-report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-report
        path: ./allure-report
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs