name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies 
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Display structure
      run: ls -R
    - name: Upload artifact allure-results
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-results
        path: ./DemoProject/allure-results
  deploy:
    runs-on: atools/chrome-headless 

    steps:
    - run: npm i -g npm@latest
    - run: npm i npm@latest
    - run: npm allure-commandline@latest
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R