name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies 
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create Report
      if: always()
      # trying to save history of previous runs if it is exists
      run: allure-cmd/bin/allure generate allure-results --clean
    - name: Upload artifact allure-report
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: allure-report
        path: ./allure-report
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@3.1.0
      if: always()
      with:
        ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: allure-report # The folder the action should deploy.
        TARGET_FOLDER: docs